# Generated by Django 3.2.8 on 2022-02-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('contents', models.CharField(max_length=3000, verbose_name='お問い合わせ内容')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
