# Generated by Django 3.2.8 on 2022-02-20 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(error_messages={'unique': '同一の商品が既に登録されています'}, max_length=100, unique=True, verbose_name='商品名')),
                ('description', models.CharField(max_length=3000, verbose_name='商品説明')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('situation', models.BooleanField(verbose_name='販売状態')),
                ('stock', models.PositiveIntegerField(verbose_name='在庫数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/product_image/images/', verbose_name='サムネイル')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(error_messages={'unique': '同一のカテゴリーが既に登録されています'}, max_length=20, unique=True, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('image', models.ImageField(upload_to='shop/product_image/images/', verbose_name='商品画像')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='対象商品')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
